language: python

sudo: false

python:
    - '2.7'
    - '3.3'
    - '3.4'
    - '3.5'
    - '3.6'
    - '3.7'

install:
    - pip install flake8 bandit
    - pip install .

script:
    - make test
    - scraper -h
