language: python

python:
    - '3.6'
    - '3.7'
    - '3.8'

install:
    - pip install regex==2019.11.1 flake8 bandit black
    - pip install .
    - npm install -g markdownlint-cli

script:
    - make test
    - scraper -h
