language: python

sudo: false

python:
    - '3.5'
    - '3.6'
    # - '3.7' -- Failing in Travis CI

install:
    - pip install flake8 bandit
    - pip install .

script:
    - make test
    - scraper -h
